# Generated by Django 3.2.4 on 2021-06-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_auto_20210626_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='quick_and_easy',
            field=models.BooleanField(default=True),
        ),
    ]
