# Generated by Django 3.2.4 on 2021-06-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_recipe_quick_and_easy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='last_made_at',
            field=models.DateField(),
        ),
    ]
