# Generated by Django 3.2.4 on 2021-07-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_recipe_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='have_made_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
