# Generated by Django 3.2.4 on 2021-07-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0008_alter_recipe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('AME', 'American'), ('CHI', 'Chinese'), ('EEU', 'Eastern European'), ('ENG', 'English'), ('FRE', 'French'), ('GER', 'German'), ('GRE', 'Greek'), ('IND', 'Indian'), ('ITA', 'Italian'), ('JPN', 'Japanese'), ('KRN', 'Korean'), ('MEX', 'Mexican'), ('OTR', 'Other'), ('SOL', 'Soul Food')], default='AME', max_length=3),
        ),
    ]
