# Generated by Django 3.2.4 on 2021-07-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0009_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('AM', 'American'), ('CH', 'Chinese'), ('EE', 'Eastern European'), ('EN', 'English'), ('FR', 'French'), ('GE', 'German'), ('GR', 'Greek'), ('IN', 'Indian'), ('IT', 'Italian'), ('JP', 'Japanese'), ('KR', 'Korean'), ('MX', 'Mexican'), ('OT', 'Other'), ('SL', 'Soul Food')], default='AM', max_length=2),
        ),
    ]
